/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as ApiAssetsKeyRouteImport } from './routes/api/assets.$key'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAssetsKeyRoute = ApiAssetsKeyRouteImport.update({
  id: '/api/assets/$key',
  path: '/api/assets/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/category/$slug': typeof CategorySlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/assets/$key': typeof ApiAssetsKeyRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/category/$slug': typeof CategorySlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/assets/$key': typeof ApiAssetsKeyRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/upload': typeof ApiUploadRoute
  '/category/$slug': typeof CategorySlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/assets/$key': typeof ApiAssetsKeyRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feed.xml'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/settings'
    | '/api/upload'
    | '/category/$slug'
    | '/posts/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/assets/$key'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed.xml'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/settings'
    | '/api/upload'
    | '/category/$slug'
    | '/posts/$slug'
    | '/tag/$slug'
    | '/admin'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/assets/$key'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/feed.xml'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/settings'
    | '/api/upload'
    | '/category/$slug'
    | '/posts/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/assets/$key'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiUploadRoute: typeof ApiUploadRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PostsSlugRoute: typeof PostsSlugRoute
  TagSlugRoute: typeof TagSlugRoute
  ApiAssetsKeyRoute: typeof ApiAssetsKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/assets/$key': {
      id: '/api/assets/$key'
      path: '/api/assets/$key'
      fullPath: '/api/assets/$key'
      preLoaderRoute: typeof ApiAssetsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FeedDotxmlRoute: FeedDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiUploadRoute: ApiUploadRoute,
  CategorySlugRoute: CategorySlugRoute,
  PostsSlugRoute: PostsSlugRoute,
  TagSlugRoute: TagSlugRoute,
  ApiAssetsKeyRoute: ApiAssetsKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
